server:
  port: ${SERVER_PORT:8080}
spring:
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test?currentSchema=test
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        max_fetch_depth: 5
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    open-in-view: false

graphql:
  servlet:
    maxQueryDepth: 3